version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL:-http://103.163.215.106:1551}
      - SKIP_ENV_VALIDATION=${SKIP_ENV_VALIDATION:-true}
    env_file:
      - .env
    restart: always
    volumes:
      - ./public:/app/public
      # Add more volume mounts as needed for development
